config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:index, :show, :create]
  get '/signup', to:'users#new', as: 'new_user'
  get '/users/:id/recordbox', to: 'users#recordbox', as: 'user_recordbox'
  get '/users/:id/recordbox/rating', to: 'users#recordbox_rating', as: 'user_recordbox_rating'
  get '/users/:id/recordbox/desc', to: 'users#recordbox_desc', as: 'user_recordbox_desc'
  get '/users/:id/recordbox/asc', to: 'users#recordbox_asc', as: 'user_recordbox_asc'
  get '/users/:id/reviewed_records', to: 'users#reviewed_records', as: 'user_reviewed_records'

  resources :records do
    collection do
      get :rating_desc
      get :released_desc
      get :released_asc
    end
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :records
  has_many :reviews, dependent: :destroy
  has_many :reviewed_records, through: :reviews, source: :record
  has_secure_password

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, length: { minimum: 4 }
  validates :email, presence: true
  validates :email, uniqueness: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :recordbox, :recordbox_rating, :recordbox_desc, :recordbox_asc, :reviewed_records]
  before_action :require_login, except: [:new, :create]

  def index
    @users = User.all
  end

  def new
    if !logged_in?
      @user = User.new
    else
      flash[:message] = "You already have an account and are logged in."
      redirect_to user_path(current_user)
    end
  end

  def show
  end

  def recordbox
    @records = @user.records
  end

  def recordbox_rating
    @records = @user.records.order(avg_review: :desc)
    render action: :recordbox
  end

  def recordbox_desc
    @records = @user.records.order(released: :desc)
    render action: :recordbox
  end

  def recordbox_asc
    @records = @user.records.order(released: :asc)
    render action: :recordbox
  end

  def reviewed_records
    @records = @user.reviewed_records
  end



  def create
    @user = User.new(user_params)
    if @user.save
      login!
      redirect_to user_path(@user)
    else
      flash.now[:message] = "<strong>Please try again. There were some errors:</strong><br>".html_safe + @user.errors.full_messages.join("<br/>").html_safe
      render :new
    end
  end


  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <h1>User Index</h1>
  <div class="container">
    <% @users.each do |user| %>
    <%= link_to user.username.titleize, user_path(user) %> <br>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1 class="text-center">Sign Up!</h1>
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <div class="form-group">
          <%= form_for @user do |f| %>
            <%= f.label :username, "Username:" %>
            <%= f.text_field :username, class: "form-control" %><br>
            <%= f.label :email, "Email:"  %>
            <%= f.text_field :email, class: "form-control" %><br>
            <%= f.label :password, "Password:" %>
            <%= f.password_field :password, class: "form-control" %><br>
            <%= f.label :password_confirmation, "Confirm Password:" %>
            <%= f.password_field :password_confirmation, class: "form-control" %><br>
            <%= f.submit "Sign Up", class: 'btn btn-primary btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/users/recordbox.html.erb
<div class="row">
    <h1 class="text-center"><%="#{@user.username.titleize}'s Recordbox"%></h1>
</div>

  <div class="text-center">
    (Count: <%= @records.count %>)
  </div>
<br>
<div class="text-center">
<strong>Sort by</strong><br>
  <%= link_to "Rating", user_recordbox_rating_path %> |
  <%= link_to "Newest", user_recordbox_desc_path %> |
  <%= link_to "Oldest", user_recordbox_asc_path %>
</div>
<br></br>
<%= render "/layouts/records_container" %>

<%= render "records/script" %>

app/views/users/reviewed_records.html.erb
<h1 class="text-center"><%="#{@user.username.titleize}'s Reviewed Records"%></h1>
<br>

<%= render "/layouts/records_container" %>

<%= render "records/script" %>

app/views/users/show.html.erb
<div class="container">

  <div class="col-md-2 col-md-offset-5"></div>
  <h1><%= @user.username.titleize %></h1>
      <% if logged_in? && authorized_user? %>
      <h3><%= @user.email %></h3>
      <%= link_to "Reviewed Records", user_reviewed_records_path %> <br>
        <%= link_to "Log Out", '/logout', {method: 'post'} %>
        <% else %>
          <%= link_to "Recordbox", user_recordbox_path %><br>
          <%= link_to "Reviewed Records", user_reviewed_records_path %> <br>
      <% end %>
      <br></br>

    <div class="row">
      <div class="pane">
        <div class="col-sm-3">
          Member Since:<br>
        <%= @user.created_at.to_date%><br><br>
        </div>

      <div class="col-sm-3">
        Total Reviews:<br>
        <%= @user.reviewed_records.count %><br><br>
      </div>

      <div class="col-sm-3">
        Records in Recordbox:<br>
        <%= @user.records.count %><br><br>
      </div>

      <div class="col-sm-3">
        Last Update:<br>
        <%= @user.records.last.updated_at.to_date unless @user.records.empty? %><br><br>
      </div>

      </div>

    </div>

</div>