config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:index, :show, :create]
  get '/signup', to:'users#new', as: 'new_user'
  get '/users/:id/recordbox', to: 'users#recordbox', as: 'user_recordbox'
  get '/users/:id/recordbox/rating', to: 'users#recordbox_rating', as: 'user_recordbox_rating'
  get '/users/:id/recordbox/desc', to: 'users#recordbox_desc', as: 'user_recordbox_desc'
  get '/users/:id/recordbox/asc', to: 'users#recordbox_asc', as: 'user_recordbox_asc'
  get '/users/:id/reviewed_records', to: 'users#reviewed_records', as: 'user_reviewed_records'

  resources :records do
    collection do
      get :rating_desc
      get :released_desc
      get :released_asc
    end
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user, optional: :true
  has_many :reviews
  has_many :reviewers, through: :reviews
  has_many :tracks, dependent: :destroy
  accepts_nested_attributes_for :tracks, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }
  has_one_attached :image

  validates :artist, presence: true
  validates :title, presence: true
  validates :label, presence: true
  validates :format, presence: true
  validates :cat, presence: true
  validates :released, presence: true
  validates :genre, presence: true
  validates :tracks, presence: true
  validate :image_validated?


  def review_avg
    self.reviews.average(:rating).to_i
  end

  scope :rating_desc, ->{ order("avg_review DESC")}
  scope :released_desc, ->{ order("released DESC")}
  scope :released_asc, ->{ order("released ASC")}

  private

  def image_validated?
    if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
      errors.add(:image, 'must be a JPEG or PNG format.')
    elsif image.attached? == false
      errors.add(:image, 'must be included')
    end
  end



end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :find_record, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:show]

  def index
    @records = Record.all
  end

  def show
  end

  def new
    @record = Record.new
    @record.tracks.build
  end

  def edit
    if @record.user == current_user
    else
      flash.now[:message] = "You don't have permision to do that!"
      redirect_to '/'
    end
  end

  def rating_desc
    @records = Record.rating_desc
    render action: :index
  end

  def released_desc
    @records = Record.released_desc
    render action: :index
  end

  def released_asc
    @records = Record.released_asc
    render action: :index
  end

  #post/patch
  #----

  def create
    @record = Record.new(record_params)
    @record.user = current_user
      if @record.save
        flash[:success] = "Record successfuly created!"
        redirect_to record_path(@record)
    else
      flash.now[:message] = "<strong>Please try again. There were some errors:</strong><br>".html_safe + @record.errors.full_messages.join("<br/>").html_safe
      render :new
    end
  end

  def update
    if @record && @record.user == current_user
      @record.update(record_params)
        if @record.save
          flash[:success] = "Record successfuly updated"
          redirect_to record_path(@record)
        else
          flash.now[:message] = "<strong>Please try again. There were some errors:</strong><br>".html_safe + @record.errors.full_messages.join("<br/>").html_safe
          render :edit
        end
    else
      flash[:message] = "Record not found or you don't have permission to do that"
      redirect_to '/'
    end
  end

  def destroy
    if @record.user == current_user
      @record.delete
      flash[:success] = "Record successfuly deleted!"
      redirect_to user_recordbox_path(current_user)
    else
      flash.now[:message] = "You don't have permision to do that!"
      redirect_to '/'
    end
  end


  private

  def find_record
    @record = Record.find(params[:id])
  end

  def record_params
    params.require(:record).permit(:artist, :title, :label, :format, :cat, :released, :genre, :image, :user_id, tracks_attributes: Track.attribute_names.map(&:to_sym).push(:_destroy))
  end

end

app/helpers/records_helper.rb
module RecordsHelper

  def review_owner
    @record.reviews.find {|r| r.reviewer == current_user}
  end


end

app/views/records/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <div class="form-group">
        <%= form_for @record do |f| %>
          <%= f.label :artist %>
          <%= f.text_field :artist, class: "form-control" %><br>
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %><br>
          <%= f.label :label %>
          <%= f.text_field :label, class: "form-control" %><br>
          <%= f.label :format %>
          <%= f.text_field :format, class: "form-control" %><br>
          <%= f.label :cat %>
          <%= f.text_field :cat, class: "form-control" %><br>
          <%= f.label :released %>
          <%= f.date_field :released, class: "form-control" %><br>
          <%= f.label :genre %>
          <%= f.text_field :genre, class: "form-control" %><br>
          <%= f.label :image %>
          <%= f.file_field :image %><br>

          <h3>Tracks</h3>
          <div class="tracks">
            <%= f.fields_for :tracks do |builder| %>
            <%= render 'track_fields', f: builder %>
            <% end %>
          </div>

            <div class="form-actions">
              <%= link_to_add_association 'Add Track', f, :tracks, data: { association_insertion_node: '.tracks', association_insertion_method: :append } %>
              <br></br>
              <%= f.submit class: 'btn btn-primary btn-block' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/records/_script.html.erb
<script>
$('.star-rating').raty({
path: '/assets/',
readOnly: true,
score: function() {
    return $(this).attr('data-score');
}
});
</script>

app/views/records/_track_fields.html.erb
<div class="nested-fields">

    <%= f.label :name, "Track Name" %>
    <%= f.text_field :name, class: "form-control" %>
    <div class="text-right">
      <%= link_to_remove_association "remove track", f %>
    </div>

</div>

app/views/records/edit.html.erb
<div class="text-center">
  <h1>Edit Record</h1>
</div>

<%= render 'form', record: @record %>

app/views/records/index.html.erb
<div class="row">
    <h1 class="text-center"> Record Index</h1>
  </div>

  <div class="text-center">
    (Count: <%= @records.count %>)
  </div>
  <br>
  <div class="text-center">
  <strong>Sort by</strong><br>
    <%= link_to "Rating", rating_desc_records_path %> |
    <%= link_to "Newest", released_desc_records_path %> |
    <%= link_to "Oldest", released_asc_records_path %>
  </div>
  <br></br>
  
  <%= render "/layouts/records_container" %>

  <%= render "script" %>

app/views/records/new.html.erb
<div class="text-center">
  <h1>Create New Record</h1>
</div>

<%= render 'form', record: @record %>

app/views/records/show.html.erb
<div class="record-show">

      <div class="record-image">
        <div class="text-center" style="width:290px; height:auto">
          <%= image_tag(@record.image, style:'width:100%') %>
        </div>
        <br>
        <%= link_to "Add Review", new_record_review_path(@record), class: 'btn btn-primary btn-block' if logged_in? && !review_owner %>
        <% if logged_in? && current_user == @record.user %>
        <%= link_to "Edit Record", edit_record_path(@record), class: 'btn btn-primary btn-block' %>
        <%= link_to "Delete Record", @record, method: :delete, data: { confirm: "Are you sure you want to delete this record?" }, class: 'btn btn-danger btn-block offset-2' %>
        <% end %>
      </div>

    <div class="record-info">
        <h2> <strong><%= @record.artist.upcase %></strong> </h2>
        <h3><%= @record.title %></h3>
        <h4><%= @record.label %></h4>
        <strong>Format:</strong> <%= @record.format %>
        <br><strong>Cat:</strong> <%= @record.cat %>
        <br><strong>Released:</strong> <%= @record.released %>
        <br><strong>Genre:</strong> <%= @record.genre %>

        <table class="table borderless">
          <tbody>
            <tr>
              <td> <h3>Tracklist</h3> </td>
              <tr>
                <% @record.tracks.each_with_index do |t, i| %>
              </tr>
              <td><%= "#{i+1} - #{t.name}" %>  </td>  <br>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>

      
        <% if !@record.reviews.empty?  %>
        <div class="reviews">
          <h2 class="text-center">Reviews</h2>

          <div class="review-info">
          <% @record.reviews.each do |review| %>
              <p> <strong> <%= link_to review.reviewer.username.titleize, user_path(review.reviewer) %> says: </strong>
                <p>"<%= review.comment %>"</p>
                <div class="star-rating" data-score=<%= review.rating %>></div><br>
                <strong> Favorite Track: </strong>
                <%= review.favorite_track %></strong><br>
                <% if logged_in? && current_user == review.reviewer %>
                <div class="text-right">
                  <%= link_to "Edit", edit_record_review_path(review.record, review) %> |
                  <%= link_to "Remove", record_review_path(review.record, review), method: :delete %>
                </div>
                <% end %>
                  ___________________________________________<br></br>

              <% end %>

          <% end %>
          </div>
      </div> 

</div>           


<%= render "script" %>