config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:index, :show, :create]
  get '/signup', to:'users#new', as: 'new_user'
  get '/users/:id/recordbox', to: 'users#recordbox', as: 'user_recordbox'
  get '/users/:id/recordbox/rating', to: 'users#recordbox_rating', as: 'user_recordbox_rating'
  get '/users/:id/recordbox/desc', to: 'users#recordbox_desc', as: 'user_recordbox_desc'
  get '/users/:id/recordbox/asc', to: 'users#recordbox_asc', as: 'user_recordbox_asc'
  get '/users/:id/reviewed_records', to: 'users#reviewed_records', as: 'user_reviewed_records'

  resources :records do
    collection do
      get :rating_desc
      get :released_desc
      get :released_asc
    end
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger text-center" role="alert">
    <h4>There were some errors:</h4>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav-demo" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">RecordboxReviews!</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-nav-demo">
      <% if logged_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Your Recordbox", user_recordbox_path(current_user) %></li>
        <li><%= link_to "Add Record", new_record_path %></li>
        <li><%= link_to "Record Index", records_path %></li>
        <li><%= link_to "User Index", users_path %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Logged in as: #{current_user.username.titleize}", current_user %>  </li>
        <li><%= link_to "Log Out", '/logout', {method: 'post'} %></a></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", '/signup' %></a></li>
        <li><%= link_to "Login", '/login' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_records_container.html.erb
<div class="records-container">
    <% @records.each do |record| %>
      <div class="record-card">
        <h4 class="text-center"> <%= record.title %></h4>
        <h5 class="text-center"> <%= record.artist.upcase  %></h5>
        <div class="star-rating text-center" data-score= <%= record.review_avg %> ></div><br>
        <div class="thumbnail">
          <%= link_to image_tag(record.image, style:'width:100%'), record_path(record) %>
        </div>
      </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecordboxReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> -->

  </head>

  <body>
      <% if flash[:message] %>
      <div class="alert alert-danger text-center"> <%= flash[:message] %></div>
      <% end %>
      </div>

      <% if flash[:success] %>
      <div class="alert alert-success text-center"> <%= flash[:success] %></div>
      <% end %>
      </div>

    <%= render "/layouts/navigation" %>

    <div class="container">
      <%= yield %>
    </div>


    <div class="container">
      <footer class="branding text-center">
          <small>&copy; 2018 <strong>Recordbox Reviews | Alejandro Sabogal</strong></small><br>
          
        </footer>
    </div>






    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="app/assets/javascripts/jquery.raty.js"></script>
    <script src="app/views/records/_script.html.erb"></script>
  </body>
</html>